[general]
caption_extension = '.txt'

[[Datasets]]
batch_size = 4
resolution = 1024

  [[datasets.subsets]]
  image_dir = 'd:\kohya_ss\examples\stable_cascade\test_dataset'
  num_repeats = 10
  class_tokens = 'toy'
  caption_extension = '.txt'
